### ISSUE TITLE
Failed Setup and AssertionError on Domekt R 400 L-H

### ISSUE THREAD

**Issue by anton4** [siku2/hass-komfovent-c5#14]
I am getting the following error in the logs and setup fails.
![image](https://github.com/siku2/hass-komfovent-c5/assets/5539972/fd5ca90b-e8c3-4a55-a77f-362b4d3f4f90)

```
This error originated from a custom integration.

Logger: custom_components.komfovent_c5
Source: custom_components/komfovent_c5/api/client.py:105
Integration: Komfovent C5 (documentation, issues)
First occurred: 22:11:32 (14 occurrences)
Last logged: 22:15:17

Unexpected error fetching komfovent_c5 data:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 81, in _async_update_data
    self.__settings = await api.Settings(self.__client).read_all()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/settings.py", line 161, in read_all
    registers = await self._client.read_many_u16(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/client.py", line 115, in read_many_u16
    await self._read_batch(batch_start, count=batch_end - batch_start)
  File "/config/custom_components/komfovent_c5/api/client.py", line 105, in _read_batch
    assert not response.isError()
AssertionError
```
I am running Home Assistant version 2023.8.2, but the same error was also with 2023.4, 2023.5, 2023.6, 2023.7.
I have tested with 0.26 and 0.33 version of hass-komfovent-c5.

When setting up modbus manually in HA configuration like so, it works:
```
modbus:
  name: "Komfovent"
  type: tcp
  host: 192.168.5.13
  port: 502
  delay: 2
  retry_on_empty: true
  close_comm_on_error: false
  message_wait_milliseconds: 200

  switches:
    - name: "Komfovent Switch Power"
      slave: 1
      address: 0
      command_on: 1
      command_off: 0

  sensors:
    - name: "Komfovent Start/Stop Status"
      address: 1999
      input_type: holding
      data_type: uint8
      scan_interval: 60
    - name: "Komfovent Current Mode"
      address: 2000
      input_type: holding
      data_type: uint16
      scan_interval: 60
...
```

**Comment by siku2** [comment]
@spectrality-github, thanks for the list. I will go over it as well.

**Comment by spectrality-github** [comment]
Made few fast changes to remove not supported registers and can confirm that now it working with my old  2015 REGO-700VE-L-EC-C5
![image](https://github.com/siku2/hass-komfovent-c5/assets/54081042/2af16607-faf5-4626-b367-37f2f9a4d32a)
![image](https://github.com/siku2/hass-komfovent-c5/assets/54081042/7be03084-feb9-4876-b82a-a83b317cc1d4)
![image](https://github.com/siku2/hass-komfovent-c5/assets/54081042/c8611a8f-09c6-47ed-b4a4-7d8df08c77db)
![image](https://github.com/siku2/hass-komfovent-c5/assets/54081042/bb4251c8-14b1-46ee-be6e-64e69359cd7b)

Also made small change in client.py, as it was not working in latest HA version with updated pymodbus version which don't support anymore params in modbus client
![image](https://github.com/siku2/hass-komfovent-c5/assets/54081042/2e06f557-18fe-407d-b04b-0072ef196032)

**Comment by siku2** [comment]
Thanks a lot for your efforts, @spectrality-github. I went ahead and created a new release including the changes.
Can you test the new version and let me know how it goes?
Same goes for you too, @anton4

**Comment by spectrality-github** [comment]
New version is working for me out-of-the-box. Thanks

Device info still shows  RHP 400 V C5 :)  but it it jus cosmetics what don't affect anything. 
![image](https://github.com/siku2/hass-komfovent-c5/assets/54081042/693d620e-349b-4741-9f2e-c466e006f2a8)
And I believe my C5 don't provide AHU name.

**Comment by siku2** [comment]
I actually removed the model name in the latest version, but existing config entries can only replace it, not remove it. If it bothers you you'll have to re-create the config entry :P

**Comment by siku2** [comment]
Can you elaborate on the missing ahu name part though? Is it empty or how can you tell that it's missing?

**Comment by spectrality-github** [comment]
In my case AHU name contains just "Komfovent"
![image](https://github.com/siku2/hass-komfovent-c5/assets/54081042/4e424331-293d-4e6f-93c5-592eb16d211f)
Thanks

**Comment by siku2** [comment]
It's the same for me as well, yeah. I don't think the AHU name is very useful unfortunately.

I'm still waiting for feedback from you, @anton4. I hope this issue can be closed.

**Comment by anton4** [comment]
I noticed that your last update requires HA 2023.9
However I am using Sungrow PV inverter integration with HA and at the moment there are modbus issues with 2023.9 version so I am still holding back the upgrade from 2023.8 to 2023.9.
Once these modbus issues are sorted out I will upgrade to 2023.9.x and try your fixed version.
![image](https://github.com/siku2/hass-komfovent-c5/assets/5539972/99dcf2bb-6e99-4ff3-9192-0285a037a163)

**Comment by siku2** [comment]
@anton4, I lowered the required version back down to 2023.08 since the changes I had to make for the new HA version are backwards compatible.
Let me know how it goes.

**Comment by anton4** [comment]
I am getting this error when trying to install version 0.3.5 and I think it's related to that in github Releases there is  Downloads missing for version 0.3.5 (see screenshot attached).

`2023-09-13 10:08:12.954 ERROR (MainThread) [custom_components.hacs] <Integration siku2/hass-komfovent-c5> No assets found for release 'tags/0.3.5'
2023-09-13 10:08:12.956 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140628372089152] Error handling message: Unknown error (unknown_error) anton4 from 215.129.19.27 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 216, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
    await self.async_install_repository()
  File "/config/custom_components/hacs/repositories/base.py", line 995, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details`

![image](https://github.com/siku2/hass-komfovent-c5/assets/5539972/5447e57e-cb80-4d1f-a252-9f927bc18c56)

**Comment by siku2** [comment]
My bad, it looks like the release automation broke.

**Comment by siku2** [comment]
@anton4, really sorry for the delay, but the release should be fixed now.

**Comment by anton4** [comment]
Thanks for the fixed release, however I am still getting AssertionError, only the line numbers have changed - 
```
2023-09-14 08:10:37.007 ERROR (MainThread) [custom_components.komfovent_c5] Unexpected error fetching komfovent_c5 data: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 91, in _async_update_data
    return await KomfoventState.read_all(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 48, in read_all
    monitoring=await api.Monitoring(client).read_all(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/monitoring.py", line 335, in read_all
    block1 = await self.read_block1(units=units, is_extended=is_extended)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/monitoring.py", line 313, in read_block1
    registers = await self._client.read_many_u16(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/client.py", line 114, in read_many_u16
    await self._read_batch(batch_start, count=batch_end - batch_start)
  File "/config/custom_components/komfovent_c5/api/client.py", line 104, in _read_batch
    assert not response.isError()
AssertionError
```
